# Generated by Django 4.0.4 on 2022-05-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
    ]
