# Generated by Django 4.0.4 on 2022-05-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_product_text_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[('four', '4gb'), ('six', '6gb'), ('eight', '8gb')], default='1', max_length=5),
        ),
    ]
