# Generated by Django 4.0.4 on 2022-05-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='variant2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='variant3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[('1', (('ram', '4'), ('rom', '64')))], default='1', max_length=5),
        ),
    ]
