# Generated by Django 4.0.4 on 2022-05-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant4_64gb',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant6_64gb',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant8_128gb',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('1', 'Red'), ('2', 'Blue'), ('3', 'Green')], default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('1', '4gb 64gb'), ('2', '6gb 64gb'), ('3', '8gb 128gb')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
