# Generated by Django 4.0.4 on 2022-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_product_brand_product_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='model_no',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('1', 'Samsung'), ('2', 'Apple'), ('3', 'Nokia')], default='1', max_length=9),
        ),
    ]
