# Generated by Django 4.0.4 on 2022-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_model_product_model_no_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Nokia', 'Nokia')], default='Samsung', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], default='Red', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('4gb 64gb', '4gb 64gb'), ('6gb 64gb', '6gb 64gb'), ('8gb 128gb', '8gb 128gb')], default='8gb 128gb', max_length=9),
        ),
    ]
