# Generated by Django 4.0.4 on 2022-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_product_brand_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('1', 'Samsung'), ('2', 'Apple'), ('3', 'Nokia')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('1', 'Red'), ('2', 'Blue'), ('3', 'Green')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('1', '4gb 64gb'), ('2', '6gb 64gb'), ('3', '8gb 128gb')], default='1', max_length=9),
        ),
    ]
