# Generated by Django 4.0.4 on 2022-05-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
