# Generated by Django 4.0.4 on 2022-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
