# Generated by Django 4.0.4 on 2022-05-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_product_variant_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_variant',
            old_name='product_id',
            new_name='product',
        ),
    ]
