# Generated by Django 4.0.4 on 2022-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_product_variant_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='color',
            field=models.CharField(choices=[('1', 'Red'), ('2', 'Blue'), ('3', 'Green')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='variant',
            field=models.CharField(choices=[('1', '4gb 64gb'), ('2', '6gb 64gb'), ('3', '8gb 128gb')], default='1', max_length=9),
        ),
    ]
