# Generated by Django 4.0.4 on 2022-05-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
