# Generated by Django 4.0.4 on 2022-05-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='times',
            field=models.DateTimeField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
