# Generated by Django 4.0.4 on 2022-05-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_order_time_order_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='times',
        ),
    ]
